name: Python tests
'on':
  push:
    branches:
      - feature/unit-testing-v2-wajahat
  pull_request:
    branches:
      - feature/unit-testing-v2-wajahat
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pwd
          cd tests/unit_test/
          # pytest *.py      
          # env:
      #   ENV_VAR_1: ${{ env.BUCKET_NAME }}
      #   ENV_VAR_2: ${{ env.OBJECT_KEY }}
      
      # - name: Load environment variables
      #   uses: decathlon/gh-actions-load-env-file@v1
      #   with:
      #     path: .env